<?php

namespace UTT\CursusBundle\Repository;

/**
 * CursusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursusRepository extends \Doctrine\ORM\EntityRepository
{
}
