<?php

namespace UTT\CursusBundle\Repository;

/**
 * ElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSemesterCursus($id)
    {
        $query = $this->_em->createQuery('SELECT Distinct s.nom FROM UTTCursusBundle:Element e JOIN e.semLabel s WHERE e.cursus=:id ');
        $query->setParameter('id', $id);
        $results = $query->getResult();

        return $results;

    }

}
