<?php

namespace UTT\CursusBundle\Repository;

/**
 * SemLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SemLabelRepository extends \Doctrine\ORM\EntityRepository
{
}
