<?php

namespace UTT\CSVBundle\Repository;

/**
 * CSVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CSVRepository extends \Doctrine\ORM\EntityRepository
{
}
