utt_cursus_homepage:
    path:     /
    defaults: { _controller: UTTCursusBundle:Cursus:index }
utt_cursus_add:
    path:     /AjouterCursus
    defaults: { _controller: UTTCursusBundle:Cursus:add }
utt_cursus_edit:
    path:     /EditCursus/{id}
    defaults: { _controller: UTTCursusBundle:Cursus:edit }
    requirements:
               id: '\d+'
