utt_cursus:
    resource: "@UTTCursusBundle/Resources/config/routing.yml"
    prefix:   /

utt_core:
    resource: "@UTTCoreBundle/Resources/config/routing.yml"
    prefix:   /

utt_etu:
    resource: "@UTTEtuBundle/Resources/config/routing.yml"
    prefix:   /etudiant

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /
