uttcsv:
    resource: "@UTTCSVBundle/Resources/config/routing.yml"
    prefix:   /csv

utt_cursus:
    resource: "@UTTCursusBundle/Resources/config/routing.yml"
    prefix:   /cursus

utt_core:
    resource: "@UTTCoreBundle/Resources/config/routing.yml"
    prefix:   /

utt_etu:
    resource: "@UTTEtuBundle/Resources/config/routing.yml"
    prefix:   /etudiant
