utt_etu_homepage:
    path:     /
    defaults: { _controller: UTTEtuBundle:Etu:index }
utt_etu_add:
        path:     /AjouterEtudiant
        defaults: { _controller: UTTEtuBundle:Etu:add }
utt_etu_view:
    path:      /{id}
    defaults: { _controller: UTTEtuBundle:Etu:view }
    requirements:
           id: '\d+'