<?php

namespace UTT\EtuBundle\Repository;

/**
 * FilliereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilliereRepository extends \Doctrine\ORM\EntityRepository
{
}
