utt_csv_homepage:
    path:     /
    defaults: { _controller: UTTCSVBundle:CSV:index }
    
utt_csv_upload:
    path:     /ImportCSV
    defaults: { _controller: UTTCSVBundle:CSV:upload }
    
utt_csv_generate:
    path:     /GenerateCSV/{id}
    defaults: { _controller: UTTCSVBundle:CSV:generate }
    requirements:
                   id: '\d+'