<?php

namespace UTT\ReglementBundle\Repository;

/**
 * AgregatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgregatRepository extends \Doctrine\ORM\EntityRepository
{
}
